### ISSUE TITLE
Python 2.7 compatibility for irc

### ISSUE THREAD

**Issue by sbraz** [jaraco/jaraco.stream#1]
Hi Jason,
This module does not seem to be compatible with Python 2.7 (at least because of `yield from`, I didn't really look further). However, [irc](https://github.com/jaraco/irc/blob/master/setup.py#L59) is still marked as compatible with Python 2.
Do you think you could make this module Python-2-compatible?

**Comment by jaraco** [comment]
I could. But IRC doesn't depend on the Python 3 code. What's the harm in the current arrangement?

**Comment by jaraco** [comment]
I do intend to maintain py 2.7 compat

**Comment by sbraz** [comment]
Well the problem is for packaging: it feels wrong to mark jaraco.stream as Python-2-compatible when some components are not. And if we don't mark it Python-2-compatible, then we can't mark irc as Python-2-compatible either.
It's no big deal though, we can wait before packaging the new version of irc.

**Comment by jaraco** [comment]
I agree. It's somewhat messy to have undeclared support in only one module. That bothers me too.

I'm slightly reluctant to backport the unrelated module, though.

I think I'll just add a note about compatibility of the buffer module to declare the compatibility expectation.

**Comment by sbraz** [comment]
> I'm slightly reluctant to backport the unrelated module, though.

Why? It's just a matter of using `for i in buf: yield i`, isn't it?

**Comment by idella** [comment]
Sorry jaraco but that leaves Louis and gentoo in a pickle

**Comment by jaraco** [comment]
> Why? It's just a matter of using for i in buf: yield i, isn't it?

Yes and no. Even just making that change masks the Python 3 syntax and creates an intermediate variable, polluting the namespace. Not that it matters _that_ much, but I'd like to start using Python 3 syntax where available, gaining experience and exposing it to users. As long as there's no use case on Python 2 that's going to rely on the buffer module, I'd prefer to keep the more clean Python 3 syntax.

> Sorry jaraco but that leaves Louis and gentoo in a pickle

I'm not sure I see the pickle. If I declare `jaraco.stream` as Python 2 compatible, but put a note in the gzip module that it requires Python 3, how is that problematic?

**Comment by jaraco** [comment]
Turns out Python 2 compatibility was a bit more complicated than the proposed change, but now tests pass on both Python 2.7 an Python 3.5.

**Comment by sbraz** [comment]
That's great, thanks!
